### ISSUE TITLE
Explore the feasibility of video playback in napari

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/movement#105]
There is a [napari-video](https://www.napari-hub.org/plugins/napari_video) plugin, but it hasn't been updated in a while.

**Comment by niksirbi** [comment]
Maybe [`numpydantic](https://github.com/p2p-ld/numpydantic#video) can also help with this?

**Comment by talmo** [comment]
FWIW, `sleap-io` which you already depend on supports a [numpy-like video proxy](https://io.sleap.ai/latest/model/#sleap_io.Video) for [lots of backends](https://io.sleap.ai/latest/reference/sleap_io/io/video/), including cv2/libav detection and fallback.

**Comment by niksirbi** [comment]
That's excellent, thank you!

**Comment by sfmig** [comment]
We explored and concluded that it is feasible.

The exact implementation will be decided in #49
