### ISSUE TITLE
Load 3D pose data from Anipose

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/movement#124]
**Is your feature request related to a problem? Please describe.**
We currently only load 2D pose predictions from SLEAP, DeepLabCut and LightningPose. We want to expand our support to 3D as well, e.g. [Anipose](https://anipose.readthedocs.io/en/latest/index.html) and/or [DANNCE](https://github.com/spoonsso/dannce).

**Describe the solution you'd like**
Anipose seems like a good starting point as we feel it's widely used. We should get ourselves some sample output files to get working on this.

**Additional context**
Working on this will also reveal if/how our current data model is inadequate for representing 3D data.

**Comment by niksirbi** [comment]
Thanks for the super-specific links. These make it extremely easy for us to also implement an anipose-loader.

**Comment by niksirbi** [comment]
Another 3D format would be that of [JARVIS](https://jarvis-mocap.github.io/jarvis-docs/).

Following [this manual](https://jarvis-mocap.github.io/jarvis-docs/getting_started/2_exploring_example/#4-predicting-poses-for-the-example-recording) we should be able to create example prediction files `data3D.csv`.

**Comment by vigji** [comment]
I have written a first draft of an anipose loader, can open a PR if this is not been addressed anywhere!

**Comment by niksirbi** [comment]
By all means do open a draft PR @vigji, none of us is working on it at the moment.
Feel free to just dump what you have in the first instance, after we take a look at it we can make plan on how to best integrate it into the existing API.
