### ISSUE TITLE
Update actions/cache@v3 -> v4

### ISSUE THREAD

**Issue by lochhh** [neuroinformatics-unit/movement#127]
When running the test_and_deploy workflow, we get the following warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Do we want to consider using dependabot to manage dependency updates?

**Comment by adamltyson** [comment]
That wouldn't help us here though right? We should just bump to `actions/cache@v4`. 

Do we have any dependencies that dependabot would help with? `movement` itself doesn't a specific version of anything.

**Comment by lochhh** [comment]
Not directly but in general for keeping "github-actions" up-to-date?

**Comment by adamltyson** [comment]
Does dependabot do that? I thought it just looked at declared dependencies?
