### ISSUE TITLE
Release on conda

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/movement#14]
As this package has non-Python dependencies, it should be released on via conda-forge as well as PyPi to enable a one-line installation.

**Comment by niksirbi** [comment]
@JoeZiminski is [this](https://conda-forge.org/docs/maintainer/adding_pkgs.html) the guide you followed for publishing `datashuttle` on `conda-forge`? Did you use `grayskull` to generate the recipe? Anything to keep in mind before I go forward with this?

For `conda-forge` we also have to officially declare the [maintainers](https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role). Who should be added apart from myself?
@adamltyson ? @lochhh ?

**Comment by adamltyson** [comment]
> For conda-forge we also have to officially declare the [maintainers](https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role). Who should be added apart from myself?
@adamltyson ? @lochhh ?

@niksirbi yes please

**Comment by lochhh** [comment]
> @JoeZiminski is [this](https://conda-forge.org/docs/maintainer/adding_pkgs.html) the guide you followed for publishing `datashuttle` on `conda-forge`? Did you use `grayskull` to generate the recipe? Anything to keep in mind before I go forward with this?

Btw, here are [some slides](https://docs.google.com/presentation/d/1jKA89NV98i-mq5LUj2LbUcVmW_dOu2u0zt081hcur8E/edit#slide=id.g27f21e9fdfa_1_253) from the Napari Software Dev Workshop on uploading to conda-forge from PyPI

**Comment by JoeZiminski** [comment]
Hey @niksirbi I used [this guide](https://levelup.gitconnected.com/publishing-your-python-package-on-conda-and-conda-forge-309a405740cf), but that looks much better! I think I generated the `meta.yaml` from the guide / copying others, so `grayskull` seems much superior.

**Comment by niksirbi** [comment]
I've started working on this, but it has currently stalled, because one of our dependencies - `sleap-io` - is not on conda-forge. I've [raised the issue with `sleap-io` developers](https://github.com/talmolab/sleap-io/issues/73), so let's wait and see.

**Comment by niksirbi** [comment]
This task is now less urgent due to the merging of #104, which means we can do a simple `pip install movement`. That said, releasing `movement` on `conda-forge` is a worthy goal anyway, and we will proceed with that once our dependencies do likewise. Both `sleap-io` and `ndx-pose` have responded positively, so it's likely that all three packages (`movement`) will be available via `conda-forge` in a few months.

**Comment by niksirbi** [comment]
This is back on the priority list for us, because we [had to go back to installing`pytables` via `conda`](#133).
Currently the only blocker appears to be https://github.com/talmolab/sleap-io/issues/73, I'll attempt a release once that is resolved.

**Comment by niksirbi** [comment]
`sleap-io` is underway to get on `conda-forge`: https://github.com/conda-forge/staged-recipes/pull/26036

**Comment by niksirbi** [comment]
On first glance that segfault also looks inscrutable to me, but I'll have a look and maybe ask colleagues who have a bit more experience with conda-forge.
The docs look cool!

**Comment by niksirbi** [comment]
@talmo no luck with it yet, but a colleague of mine suggested [testing the staged recipe locally](https://conda-forge.org/docs/maintainer/adding_pkgs/#running-tests-locally-for-staged-recipes) as a debugging approach (in case you haven't tried that already).

**Comment by niksirbi** [comment]
I've started drafting the conda-forge recipe [here](https://github.com/niksirbi/staged-recipes/tree/add-movement).

**Comment by adamltyson** [comment]
This is now on conda-forge :tada:. I've raised https://github.com/neuroinformatics-unit/movement/issues/254 to track documenting this.
