### ISSUE TITLE
Consider adding a distance and speed property to accessor

### ISSUE THREAD

**Issue by sfmig** [neuroinformatics-unit/movement#147]
From the kinematics tutorial PR review:

We could add a "distance" property in our accessor to access directly the distance travelled, e.g:
```python
distance_travelled = ds.move.distance
```
Similarly with speed.

**Comment by niksirbi** [comment]
Maybe `ds.cumulative_displacement(from=0, to=100)`? Because we will literally calculate it as ` cumsum` of the displacement.

**Comment by niksirbi** [comment]
See exhaustive discussion in #162

**Comment by sfmig** [comment]
@niksirbi @lochhh seems like we can close this now?

**Comment by lochhh** [comment]
or edit this to add more convenience methods to the accessor, e.g. `compute_speed`, `compute_distance_travelled` as suggested [here](https://github.com/neuroinformatics-unit/movement/issues/162#issuecomment-2085993924)?

**Comment by niksirbi** [comment]
Yeah, i'd keep it open, because we may consider adding those convenience methods.

**Comment by niksirbi** [comment]
Consider calling distance "path length"

**Comment by niksirbi** [comment]
We've decided to refer to "distance travelled" as `path_length`, to avoid confusion with pairwise distances (see #277).

While implementing the `compute_path_length()` function, I encountered a dilemma on how to handle missing values, see [discussion on zulip](https://neuroinformatics.zulipchat.com/#narrow/stream/406001-Movement/topic/Path.20length.20with.20missing.20values).
