### ISSUE TITLE
Log to the console rather than `print()`

### ISSUE THREAD

**Issue by lochhh** [neuroinformatics-unit/movement#235]
I assume @VascoSch92 meant that this should be logged to the console rather than printed (e.g. so verbosity can be changed by third parties).

_Originally posted by @adamltyson in https://github.com/neuroinformatics-unit/movement/pull/209#discussion_r1668932130_

When reporting number of NaNs in filtering, we currently use a [`print` statement](https://github.com/neuroinformatics-unit/movement/blob/43f17d7e86443c3e76e2a1a0ae6b61f58c4db472/movement/filtering.py#L73) to print this to the console, whilst also logging this to the `log` attribute of a DataArray.

**Comment by adamltyson** [comment]
In general (but not necessarily absolutely) I think `movement` should avoid printing things to the console. This could get annoying if a user has a script that repeats a process many times. It should be possible for the user to configure what gets printed using the logging module.

**Comment by niksirbi** [comment]
I agree on this principle. 

In this case, it's very useful to quickly see the number of NaNs before/after an operation. Given the new utility functions that @lochhh has nicely refactored into the [`utils/reports.py` module](https://github.com/neuroinformatics-unit/movement/pull/209/files#diff-1e33df17021f110b72851e80a760797c5014b0bfbd50db94e10fde636b2282e5), what would be our recommended way for viewing the report (e.g. in a notebook cell)?

One way would be for `report_nan_values()` to also return the report as a string, so one can do `print(report_nan_values(ds))`. Or are there easier ways of doing this by configuring the logger to show INFO in the cell output?

**Comment by adamltyson** [comment]
I think I wouldn't expect to use logging to see this in a notebook necessarily, but an explicit call, so something like `print(report_nan_values(ds))`

**Comment by niksirbi** [comment]
I agree, so perhaps we should modify that function in #209 to return the string?

**Comment by niksirbi** [comment]
Thanks @lochhh ! We can close this issue once I approve #209 and we merge it.
