### ISSUE TITLE
Reorder dimensions to start with space and time

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/movement#236]
**Is your feature request related to a problem? Please describe.**
In our current [dataset structure](http://127.0.0.1:3000/docs/build/html/getting_started/movement_dataset.html) the order of `xarray` dimensions is: `time`, `individuals`, `keypoints`, `space`.

This is not very intuitive, namely because `time` and `space` are the most essential dimensions which should always exist regardless of how motion was tracked. As we move toward supporting more types of data, and possibly making non-spacetime dimensions optional (e.g. create `keypoints` only if more than 1 is present, and ditto for `individuals`), and it makes more sense to put the "essential" dimensions at the beginning and the optional ones at the end.

This was brought up by @sfmig, and we both think this would make sense.

**Describe the solution you'd like**
Reorder dimensions in order of "essentiality": `time`, `space`, `keypoints`,  `individuals`, `views` (if we adopt #196).
This shouldn't be too hard as we could simply add xarray's [`transpose()`](https://docs.xarray.dev/en/stable/user-guide/reshaping.html#reordering-dimensions) methods at the end of our loading functions to get the desired order. But we would have to adapt validators (related to #210), tests and docs.

**Describe alternatives you've considered**
- `space`, `time`, `keypoints`, `individual`, `views`
- Keep things as they are, don't fix it if it ain't broken?

**Additional context**
- [Discussions](https://neuroinformatics.zulipchat.com/#narrow/stream/406001-Movement/topic/Support.20single.20individual.20data.20without.20the.20.60individuals.60.20dim) with @vigji on essential vs optional dimensions.
- Support for multiple views [issue](https://github.com/neuroinformatics-unit/movement/issues/196) and PR #197 
- On re-designing the validators: #210

**Comment by vigji** [comment]
I think this would be important yes! Even with the option of optional dimensions, keeping the essential first would be very relevant
