### ISSUE TITLE
Unexpected indentations in `movement.validators.files.ValidVIATracksCSV` docs

### ISSUE THREAD

**Issue by lochhh** [neuroinformatics-unit/movement#252]
**Describe the bug**
In #219 docs build succeeds with the following warnings (and errors): 

> movement\movement\validators\files.py:docstring of movement.validators.files.ValidVIATracksCSV.csv_file_contains_tracked_bboxes:6: ERROR: Unexpected indentation.
> movement\movement\validators\files.py:docstring of movement.validators.files.ValidVIATracksCSV.csv_file_contains_tracked_bboxes:7: WARNING: Block quote ends without a blank line; unexpected unindent.
> movement\movement\validators\files.py:docstring of movement.validators.files.ValidVIATracksCSV.csv_file_contains_valid_frame_numbers:5: ERROR: Unexpected indentation.
>movement\movement\validators\files.py:docstring of movement.validators.files.ValidVIATracksCSV.csv_file_contains_valid_frame_numbers:6: WARNING: Block quote ends without a blank line; unexpected unindent.

While this has since been rectified in #245, the documentation is not rendering as intended (see example screenshot below).
 
**Screenshots**
![image](https://github.com/user-attachments/assets/4ce55aa7-3680-4535-9b95-ffd8206e3a05)

**Comment by niksirbi** [comment]
Thanks for catching (and fixing) this!

**Comment by sfmig** [comment]
thanks @lochhh!

I was confused about this actually... do you know why the doc building succeeds even if there are errors? Should we change this behaviour (is it possible)?

**Comment by lochhh** [comment]
> thanks @lochhh!
> 
> I was confused about this actually... do you know why the doc building succeeds even if there are errors? Should we change this behaviour (is it possible)?

Here it says [build succeeded with warnings](https://github.com/neuroinformatics-unit/movement/actions/runs/10039498360/job/27743563001#step:2:807) - only when we look into the warnings, we see that there are "errors". If we think warnings are overly permissive, there is the[ --fail-on-warning flag](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-W) to treat warnings as errors, causing build to fail.

**Comment by sfmig** [comment]
I found a relevant open issue in sphinx-docs [here](https://github.com/sphinx-doc/sphinx/issues/10397).

It feels a bit annoying...
