### ISSUE TITLE
Do we need a `validate()` method in move accessor?

### ISSUE THREAD

**Issue by sfmig** [neuroinformatics-unit/movement#257]
**Is your feature request related to a problem? Please describe.**
While reviewing PR #255, @lochhh pointed out that with a poses datasets we only use the `move.validate()` method when saving the dataset to an output file.

The PR extends the move accessor to bboxes datasets, including the `move.validate()` method, and adds a test to cover the case of validating a bboxes dataset (since we don't have an equivalent `save_bboxes` module yet).

This raised the question: do we need this method? 

**Describe the solution you'd like**
For now extending the existing accessor methods and corresponding tests makes sense to me, but we may want to consider if this is necessary and if it will be a burden going forwards. 

**Describe alternatives you've considered**
\

**Additional context**
\

**Comment by lochhh** [comment]
Note also that we have `validator` modules - could we (as with other move methods, e.g. compute kinematics) use any of these in move.validate?

**Comment by niksirbi** [comment]
We could get rid of it in principle. As stated above, we only use it in one place (prior to saving).

The original idea was to use `validate()` in many places, e.g. before computing derivatives. That said, as `movement` has become more flexible we tend to do more specific validations depending on what a specific function/method needs, so the case for a general dataset validation method has weakened.

Under the hood the `validate()` method checks for the presence of expected dimensions and data variable before forwarding the rest of the checks to `ValidPosesDataset` or `ValidBboxesDataset`.
```python
self._validate_dims()
self._validate_data_vars()
```

If we were to remove `validate()`, we should find another place for doing these checks (perhaps in the `save_poses.py` module itself?).

**Comment by niksirbi** [comment]
We now are getting read of this validation as part of #322.
The functionalities of `self._validate_dims()` and `self._validate_data_vars()` are being transferred to the `save_poses.py` module, i.e. where they are actually being used. The calls to `ValidPosesDataset` and `ValidBboxesDataset`prior to saving don't happen anymore, they were too restrictive in my opinion.
