### ISSUE TITLE
Update pandas minimum requirement for Python 3.12

### ISSUE THREAD

**Issue by lochhh** [neuroinformatics-unit/movement#263]
In PR #259 we pinned pandas to <2.2.2 (which requires numpy<2) on Python 3.12. We suspect this is an [incompatibility issue between pytables and numpy>=2.0](https://github.com/PyTables/PyTables/issues/1172) as tests were failing at `pd.read_hdf()` (pandas uses pytables for reading and writing HDF5 files). This issue tracks the temporary workaround until pytables releases a new version that resolves the incompatibility. Once this is available, we will need to revert the PR.

**Comment by sfmig** [comment]
new [pytables release](https://github.com/PyTables/PyTables/releases/tag/v3.10.0) 🥳 , should be compatible with numpy 2.0

**Comment by lochhh** [comment]
`numpy < 2` is still being installed in the environment in [Pytables](https://github.com/PyTables/PyTables/releases/tag/v3.10.0) (see relevant [PyTables issue](https://github.com/PyTables/PyTables/issues/1200))
