### ISSUE TITLE
Remove equidistant time-spacing assumption in computing approximate derivative

### ISSUE THREAD

**Issue by lochhh** [neuroinformatics-unit/movement#268]
Currently when computing approximate derivatives, we assume equidistant time-spacing with a fixed `dt`:
https://github.com/neuroinformatics-unit/movement/blob/e7ccfe50f65b38dc1a05fc78e1a324df808d6198/movement/analysis/kinematics.py#L105-L113

We should instead provide the actual `time` axis values, i.e. `data.coords["time"].values`.
Since we do not need to compute derivatives along multiple axes (what [`np.gradient()`](https://numpy.org/doc/stable/reference/generated/numpy.gradient.html#numpy.gradient) can do and [`xr.differentiate()`](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.differentiate.html) can't), an even simpler solution would be to use [`xr.differentiate()`](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.differentiate.html) (as @sfmig has pointed out in #265), replacing the above lines with:
```python
for _ in range(order): 
     result = result.differentiate("time")
```

**Comment by sfmig** [comment]
I wonder if they differ in performance - maybe we could run a quick time test comparing our current implementation and `differentiate` 🤔

**Comment by niksirbi** [comment]
This sounds like an unambiguously good idea to me 👍🏼

**Comment by niksirbi** [comment]
I'm also all in for using `xr.differentiate()`.

**Comment by lochhh** [comment]
> I wonder if they differ in performance - maybe we could run a quick time test comparing our current implementation and `differentiate` 🤔

```python
# input:
dlc_ds.postion.shape = (59999, 2, 12, 2)

# xr.differentiate
%%timeit
dlc_ds.position.differentiate("time")
# 24.2 ms ± 1.56 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

# numpy
result = xr.apply_ufunc(
    np.gradient,
    dlc_ds.position,
    dlc_ds.time.values,
    kwargs={"axis": 0},
)
# 23.4 ms ± 652 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
but because we need to reindex after applying np.gradient, this takes longer

```python
%%timeit
result = xr.apply_ufunc(
    np.gradient,
    dlc_ds.position,
    dlc_ds.time.values,
    kwargs={"axis": 0},
)
result = result.reindex_like(dlc_ds.position)
# 32 ms ± 1.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by sfmig** [comment]
@lochhh thanks for timing it 🤩
